version: '3'

services:
  haproxy:
    image: haproxy:1.8.14
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      main:
        ipv4_address: 172.18.0.2

  app:
    image: php:7.2-apache
    external_links:
      - mysql:db
    volumes:
      - ./php/example:/var/www/html
    networks:
      main:
        ipv4_address: 172.18.0.10

  mysql:
    image: mysql:8.0.12
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environments:
      # $$ for escaping of $: convert $$ to $
      - MYSQL_ROOT_PASSWORD=on!yforte$$t #on!yforte$t
      #- MYSQL_USER=myuser
      #- MYSQL_PASSWORD=myPa$$sw0rd #password: mYpas$w0rd
    networks:
      main:
        ipv4_address: 172.18.0.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    external_links:
      - mysql:db
    networks:
      main:
        ipv4_address: 172.18.0.5

networks: 
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24