version: '3'

services:
  certbot:
    image: certbot/certbot:latest
    command: certbot certonly --standalone -d ${URL_APP} -d ${URL_PHPMYADMIN} --agree-tos --non-interactive --http-01-port=${PORT_CERTBOT}
    volumes:
      - ${VOLUME_CERTBOT_CERTS}:/etc/letsencrypt
    networks:
      main:
        ipv4_address: ${IPV4_ADDR_CERTBOT}

networks: 
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_CONFIG_SUBNET}