version: '3'

services:
  certbot-app:
    image: certbot/certbot:latest
    container_name: certbot
    command: [
      "certonly", 
      "--standalone", 
      "--email", "${CERTBOT_ISSUER_EMAIL}",
      "-d", "${URL_APP}",
      "--agree-tos", 
      "--non-interactive", 
      "--http-01-port=${PORT_CERTBOT}"
    ]
    volumes:
      - ${VOLUME_CERTBOT_CERTS}:/etc/letsencrypt
      - ${VOLUME_CERTBOT_LOG}:/var/log/letsencrypt
    networks:
      main:
        ipv4_address: ${IPV4_ADDR_CERTBOT}

  certbot-phpmyadmin:
    image: certbot/certbot:latest
    container_name: certbot
    command: [
      "certonly", 
      "--standalone", 
      "--email", "${CERTBOT_ISSUER_EMAIL}",
      "-d", "${URL_PHPMYADMIN}",
      "--agree-tos", 
      "--non-interactive", 
      "--http-01-port=${PORT_CERTBOT}"
    ]
    volumes:
      - ${VOLUME_CERTBOT_CERTS}:/etc/letsencrypt
      - ${VOLUME_CERTBOT_LOG}:/var/log/letsencrypt
    networks:
      main:
        ipv4_address: ${IPV4_ADDR_CERTBOT}

networks: 
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_CONFIG_SUBNET}
